### ISSUE TITLE
change code/infrastructure to allow for reruns in case of failure

### ISSUE THREAD

**Issue by fritzel56** [fritzel56/hot-potatoes#3]
for 1/10 runs so far, received this error:
Traceback (most recent call last): File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 346, in run_http_function result = _function_handler.invoke_user_function(flask.request) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function return call_user_function(request_or_event) File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 210, in call_user_function return self._user_function(request_or_event) File "/user_code/main.py", line 68, in kickoff pct[ticker] = get_yearly_return(ticker) File "/user_code/main.py", line 17, in get_yearly_return jsonList = json.loads(tree) File "/opt/python3.7/lib/python3.7/json/__init__.py", line 348, in loads return _default_decoder.decode(s) File "/opt/python3.7/lib/python3.7/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/opt/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
which implies something went wrong when fetching the website. would like to do something so it would try again later.

**Comment by fritzel56** [comment]
Was originally opened when I was thinking of having it only run once a month. Now that I have a system by which it can run daily and only email when the data changes, this is no longer needed.
